name: Cleanup Old Alerts (Daily)

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pymongo python-dotenv

      - name: Run cleanup script
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          MONGO_DB: ${{ secrets.MONGO_DB }}
          ALERTS_COLLECTION: ${{ secrets.ALERTS_COLLECTION }}
        run: python cleanup_old_alerts.py
