name: Top Changes (Categories) — Hourly

on:
  schedule:
    - cron: "12 * * * *"   # runs hourly at :12 UTC (make sure your detector runs earlier, e.g. :05)
  workflow_dispatch:
    inputs:
      SNAPSHOT_DATE:
        description: "Manual override (UTC day) YYYY-MM-DD. Leave blank for auto (today/yesterday fallback)."
        required: false

jobs:
  build-top-changes:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    concurrency:
      group: top-changes-hourly
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pymongo python-dotenv

      # If your detector writes near the top of the hour, tiny buffer helps ensure alerts exist.
      - name: Small buffer
        run: sleep 10

      - name: Run category snapshots
        env:
          # REQUIRED secrets
          MONGO_URI: ${{ secrets.MONGO_URI }}
          MONGO_DB: ${{ secrets.MONGO_DB }}
          ALERTS_COLLECTION: ${{ secrets.ALERTS_COLLECTION }}

          # OUTPUT collections (you can rename these if you want)
          TOP_STICKERS_COLLECTION: top_stickers_daily
          TOP_WEAPONS_COLLECTION:  top_weapons_daily
          TOP_CASES_COLLECTION:    top_cases_daily

          # Tuning
          TOP_LIMIT: "50"
          TOP_METRIC: "pct"              # or "abs"
          DISABLE_FALLBACK: "0"          # set "1" to prevent fallback to yesterday

          # Manual override from workflow_dispatch
          SNAPSHOT_DATE: ${{ github.event.inputs.SNAPSHOT_DATE }}
        run: |
          python top_changes_current_day.py
